const hospitalsData = [
  {
    name: 'Ruby Hall Clinic',
    type: 'Multispeciality',
    area: 'Shivajinagar',
    address: '40, Sassoon Road, Near Pune Railway Station, Sangamvadi, Pune 411001',
    phone: '020-66455100',
    emergencyAvailable: true,
    emergencyPhone: '020-26163391',
    departments: ['Cardiology', 'Oncology', 'Neurology', 'Organ Transplant', 'Trauma & Emergency', 'Orthopedics'],
    openingHours: '24/7 Emergency & Inpatient Care',
    website: 'https://rubyhall.com',
    googleMapsUrl: 'https://maps.google.com/?q=Ruby+Hall+Clinic+Pune',
    image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&q=80&w=800',
    rating: 4.8,
    bedCount: 750,
    isVerified: true,
    verificationNote: 'NABH Accredited & Verified by ClinicCare'
  },
  {
    name: 'Deenanath Mangeshkar Hospital & Research Center',
    type: 'Multispeciality',
    area: 'Kothrud',
    address: 'Erandwane, Near Mhatre Bridge, Off Karve Road, Pune 411004',
    phone: '020-40151000',
    emergencyAvailable: true,
    emergencyPhone: '020-49153000',
    departments: ['Pediatrics', 'Cardiology', 'Obstetrics & Gynaecology', 'Gastroenterology', 'Dialysis', 'ICU'],
    openingHours: '24/7 Emergency & Inpatient Care',
    website: 'https://dmhospital.org',
    googleMapsUrl: 'https://maps.google.com/?q=Deenanath+Mangeshkar+Hospital+Pune',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800',
    rating: 4.9,
    bedCount: 850,
    isVerified: true,
    verificationNote: 'NABH Accredited & Verified by ClinicCare'
  },
  {
    name: 'Sahyadri Super Speciality Hospital, Deccan',
    type: 'Multispeciality',
    area: 'Deccan',
    address: 'Plot No. 30-C, Erandvane, Karve Road, Deccan Gymkhana, Pune 411004',
    phone: '020-67215000',
    emergencyAvailable: true,
    emergencyPhone: '020-67215100',
    departments: ['Neurosciences', 'Hematology', 'Bone Marrow Transplant', 'Cardiology', 'Emergency Medicine'],
    openingHours: '24/7 Emergency & Inpatient Care',
    website: 'https://sahyadrihospital.com',
    googleMapsUrl: 'https://maps.google.com/?q=Sahyadri+Super+Speciality+Hospital+Deccan+Pune',
    image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=800',
    rating: 4.7,
    bedCount: 220,
    isVerified: true,
    verificationNote: 'NABH Accredited & Verified by ClinicCare'
  },
  {
    name: 'Jehangir Hospital',
    type: 'Multispeciality',
    area: 'Shivajinagar',
    address: '32, Sassoon Road, Opposite Pune Railway Station, Pune 411001',
    phone: '020-66819999',
    emergencyAvailable: true,
    emergencyPhone: '020-26050550',
    departments: ['Critical Care', 'Cardiac Sciences', 'Orthopedics & Joint Replacement', 'Emergency', 'Pediatrics'],
    openingHours: '24/7 Emergency & Inpatient Care',
    website: 'https://jehangirhospital.com',
    googleMapsUrl: 'https://maps.google.com/?q=Jehangir+Hospital+Pune',
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&q=80&w=800',
    rating: 4.8,
    bedCount: 350,
    isVerified: true,
    verificationNote: 'NABH Accredited & Verified by ClinicCare'
  },
  {
    name: 'Sassoon General Hospital & B.J. Medical College',
    type: 'Government',
    area: 'Shivajinagar',
    address: 'Jai Prakash Narayan Road, Near Pune Railway Station, Pune 411001',
    phone: '020-26128000',
    emergencyAvailable: true,
    emergencyPhone: '020-26128000',
    departments: ['Trauma Center', 'General Surgery', 'General Medicine', 'Pediatrics', 'Burn Care', 'Blood Bank'],
    openingHours: '24/7 Free Government Tertiary Care & Trauma',
    website: 'https://bjmcpune.org',
    googleMapsUrl: 'https://maps.google.com/?q=Sassoon+General+Hospital+Pune',
    image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&q=80&w=800',
    rating: 4.3,
    bedCount: 1300,
    isVerified: true,
    verificationNote: 'Government Medical College Hospital & Verified by ClinicCare'
  },
  {
    name: 'Jupiter Hospital Pune',
    type: 'Multispeciality',
    area: 'Baner',
    address: 'Near Prathamesh Park, Baner-Balewadi Link Road, Baner, Pune 411045',
    phone: '020-27992799',
    emergencyAvailable: true,
    emergencyPhone: '020-27992799',
    departments: ['Organ Transplant', 'Cardiac Sciences', 'Oncology', 'Robotic Surgery', 'Neurosciences', 'Emergency'],
    openingHours: '24/7 Emergency & Inpatient Care',
    website: 'https://jupiterhospital.com',
    googleMapsUrl: 'https://maps.google.com/?q=Jupiter+Hospital+Baner+Pune',
    image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&q=80&w=800',
    rating: 4.9,
    bedCount: 350,
    isVerified: true,
    verificationNote: 'NABH & NABL Accredited & Verified by ClinicCare'
  },
  {
    name: 'Manipal Hospital Kharadi',
    type: 'Multispeciality',
    area: 'Kharadi',
    address: 'Survey No. 22/2A, Near Nyati Empire, Kharadi Bypass, Pune 411014',
    phone: '020-61656666',
    emergencyAvailable: true,
    emergencyPhone: '020-61656666',
    departments: ['Emergency & Trauma', 'Cardiology', 'Orthopedics', 'Pediatrics', 'Neurology'],
    openingHours: '24/7 Emergency & Inpatient Care',
    website: 'https://manipalhospitals.com',
    googleMapsUrl: 'https://maps.google.com/?q=Manipal+Hospital+Kharadi+Pune',
    image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&q=80&w=800',
    rating: 4.7,
    bedCount: 150,
    isVerified: true,
    verificationNote: 'NABH Accredited & Verified by ClinicCare'
  },
  {
    name: 'Poona Hospital and Research Centre',
    type: 'Multispeciality',
    area: 'Sadashiv Peth',
    address: '27, Sadashiv Peth, Near Alka Talkies, Pune 411030',
    phone: '020-66096000',
    emergencyAvailable: true,
    emergencyPhone: '020-66096000',
    departments: ['Nephrology & Dialysis', 'Cardiology', 'General Surgery', 'Obstetrics', 'Orthopedics'],
    openingHours: '24/7 Emergency & Inpatient Care',
    website: 'https://poonahospital.org',
    googleMapsUrl: 'https://maps.google.com/?q=Poona+Hospital+and+Research+Centre+Pune',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800',
    rating: 4.6,
    bedCount: 300,
    isVerified: true,
    verificationNote: 'NABH Accredited & Verified by ClinicCare'
  },
  {
    name: 'KEM Hospital (King Edward Memorial Hospital)',
    type: 'Multispeciality',
    area: 'Rasta Peth',
    address: '489, Rasta Peth, Sardar Moodliar Road, Pune 411011',
    phone: '020-66037300',
    emergencyAvailable: true,
    emergencyPhone: '020-26061000',
    departments: ['NICU', 'Pediatrics', 'Obstetrics', 'Dialysis', 'General Surgery', 'Cardiology'],
    openingHours: '24/7 Emergency & Inpatient Care',
    website: 'https://kemhospitalpune.org',
    googleMapsUrl: 'https://maps.google.com/?q=KEM+Hospital+Pune',
    image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=800',
    rating: 4.7,
    bedCount: 550,
    isVerified: true,
    verificationNote: 'NABH Accredited & Verified by ClinicCare'
  },
  {
    name: 'Yashwantrao Chavan Memorial Hospital (YCMH)',
    type: 'Government',
    area: 'Pimpri',
    address: 'Sant Tukaram Nagar, Pimpri, Pimpri-Chinchwad, Pune 411018',
    phone: '020-27422500',
    emergencyAvailable: true,
    emergencyPhone: '020-27422500',
    departments: ['Emergency & Trauma', 'General Medicine', 'Orthopedics', 'Pediatrics', 'Burn Unit', 'Blood Bank'],
    openingHours: '24/7 Government Emergency & Tertiary Services',
    website: 'https://pcmcindia.gov.in',
    googleMapsUrl: 'https://maps.google.com/?q=YCM+Hospital+Pimpri+Pune',
    image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&q=80&w=800',
    rating: 4.2,
    bedCount: 750,
    isVerified: true,
    verificationNote: 'PCMC Municipal Hospital & Verified by ClinicCare'
  },
  {
    name: 'Sancheti Institute for Orthopaedics and Rehabilitation',
    type: 'Speciality',
    area: 'Shivajinagar',
    address: '16, Shivajinagar, Narveer Tanaji Wadi, Pune 411005',
    phone: '020-28999999',
    emergencyAvailable: true,
    emergencyPhone: '020-25539500',
    departments: ['Orthopedics', 'Joint Replacement', 'Spine Surgery', 'Sports Medicine', 'Trauma Rehabilitation'],
    openingHours: '24/7 Emergency Trauma & Orthopedic Care',
    website: 'https://sanchetihospital.org',
    googleMapsUrl: 'https://maps.google.com/?q=Sancheti+Hospital+Pune',
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&q=80&w=800',
    rating: 4.9,
    bedCount: 200,
    isVerified: true,
    verificationNote: 'NABH Accredited & Verified by ClinicCare'
  },
  {
    name: 'Aditya Birla Memorial Hospital',
    type: 'Multispeciality',
    area: 'Chinchwad',
    address: 'Aditya Birla Hospital Marg, Thergaon, Chinchwad, Pune 411033',
    phone: '020-30717500',
    emergencyAvailable: true,
    emergencyPhone: '020-40707500',
    departments: ['Emergency & Trauma', 'Cardiology', 'Oncology', 'Nephrology', 'Critical Care', 'Neurosciences'],
    openingHours: '24/7 Emergency & Multi-Specialty Care',
    website: 'https://adityabirlahospital.com',
    googleMapsUrl: 'https://maps.google.com/?q=Aditya+Birla+Memorial+Hospital+Chinchwad+Pune',
    image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&q=80&w=800',
    rating: 4.8,
    bedCount: 500,
    isVerified: true,
    verificationNote: 'JCI & NABH Accredited & Verified by ClinicCare'
  },
  {
    name: 'Inlaks and Budhrani Hospital',
    type: 'Multispeciality',
    area: 'Koregaon Park',
    address: '7-9, Koregaon Park, Near Bund Garden, Pune 411001',
    phone: '020-66099999',
    emergencyAvailable: true,
    emergencyPhone: '020-26123080',
    departments: ['Oncology & Radiation', 'Cardiology', 'Nephrology', 'General Surgery', 'Emergency'],
    openingHours: '24/7 Emergency Care',
    website: 'https://sadhuvaswani.org/hospitals',
    googleMapsUrl: 'https://maps.google.com/?q=Inlaks+and+Budhrani+Hospital+Pune',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800',
    rating: 4.6,
    bedCount: 250,
    isVerified: true,
    verificationNote: 'NABH Accredited & Verified by ClinicCare'
  },
  {
    name: 'Sahyadri Super Speciality Hospital, Hadapsar',
    type: 'Multispeciality',
    area: 'Hadapsar',
    address: 'Near Magarpatta City Entrance, Pune-Solapur Road, Hadapsar, Pune 411028',
    phone: '020-67298888',
    emergencyAvailable: true,
    emergencyPhone: '020-67298888',
    departments: ['Critical Care', 'Obstetrics & Gynaecology', 'Pediatrics', 'Cardiology', 'Emergency Medicine'],
    openingHours: '24/7 Emergency & Multi-Specialty',
    website: 'https://sahyadrihospital.com',
    googleMapsUrl: 'https://maps.google.com/?q=Sahyadri+Hospital+Hadapsar+Pune',
    image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=800',
    rating: 4.7,
    bedCount: 150,
    isVerified: true,
    verificationNote: 'NABH Accredited & Verified by ClinicCare'
  },
  {
    name: 'Noble Hospital',
    type: 'Multispeciality',
    area: 'Hadapsar',
    address: '153, Magarpatta City Road, Hadapsar, Pune 411013',
    phone: '020-66285000',
    emergencyAvailable: true,
    emergencyPhone: '020-66285000',
    departments: ['Emergency Trauma', 'Orthopedics', 'Cardiology', 'Neurology', 'Pulmonology', 'Blood Bank'],
    openingHours: '24/7 Emergency & Inpatient Care',
    website: 'https://noblehospitalspune.com',
    googleMapsUrl: 'https://maps.google.com/?q=Noble+Hospital+Hadapsar+Pune',
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&q=80&w=800',
    rating: 4.7,
    bedCount: 300,
    isVerified: true,
    verificationNote: 'NABH Accredited & Verified by ClinicCare'
  },
  {
    name: 'Dr. D. Y. Patil Medical College & Hospital',
    type: 'Multispeciality',
    area: 'Pimpri',
    address: 'Sant Tukaram Nagar, Pimpri, Pune 411018',
    phone: '020-27805100',
    emergencyAvailable: true,
    emergencyPhone: '020-27805100',
    departments: ['Organ Transplant', 'Trauma Unit', 'Cardiac Surgery', 'Nephrology', 'Medical Oncology'],
    openingHours: '24/7 Emergency & Super Speciality Care',
    website: 'https://medical.dpu.edu.in',
    googleMapsUrl: 'https://maps.google.com/?q=DY+Patil+Hospital+Pimpri+Pune',
    image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&q=80&w=800',
    rating: 4.8,
    bedCount: 1200,
    isVerified: true,
    verificationNote: 'NABH & NABL Accredited & Verified by ClinicCare'
  },
  {
    name: 'AIMS Hospital (Amrita Institute)',
    type: 'Multispeciality',
    area: 'Dhankawadi',
    address: 'Survey No. 154, Near Shankar Maharaj Math, Pune-Satara Road, Dhankawadi, Pune 411043',
    phone: '020-24364444',
    emergencyAvailable: true,
    emergencyPhone: '020-24364444',
    departments: ['General Medicine', 'Pediatrics', 'Orthopedics', 'Cardiology', 'ICU'],
    openingHours: '24/7 Emergency Services',
    website: 'https://aimshospitalpune.com',
    googleMapsUrl: 'https://maps.google.com/?q=AIMS+Hospital+Dhankawadi+Pune',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800',
    rating: 4.5,
    bedCount: 100,
    isVerified: true,
    verificationNote: 'Verified by ClinicCare Healthcare Verification Team'
  },
  {
    name: 'Bharati Hospital and Research Centre',
    type: 'Multispeciality',
    area: 'Katraj',
    address: 'Pune-Satara Road, Dhankawadi, Katraj, Pune 411043',
    phone: '020-24373226',
    emergencyAvailable: true,
    emergencyPhone: '020-24373226',
    departments: ['Emergency Care', 'Cardiology', 'Radiology', 'Nephrology', 'Burn Unit', 'Blood Bank'],
    openingHours: '24/7 Emergency & Multi-Specialty',
    website: 'https://bharatihospital.com',
    googleMapsUrl: 'https://maps.google.com/?q=Bharati+Hospital+Katraj+Pune',
    image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=800',
    rating: 4.6,
    bedCount: 850,
    isVerified: true,
    verificationNote: 'NABH Accredited & Verified by ClinicCare'
  },
  {
    name: 'Lokmanya Hospital Chinchwad',
    type: 'Speciality',
    area: 'Chinchwad',
    address: 'Telco Road, Near Chinchwad Railway Station, Chinchwad, Pune 411033',
    phone: '020-66355555',
    emergencyAvailable: true,
    emergencyPhone: '020-66355555',
    departments: ['Orthopedics', 'Robotic Joint Replacement', 'Emergency Trauma', 'Spine Surgery'],
    openingHours: '24/7 Trauma Care Center',
    website: 'https://lokmanyahospitals.in',
    googleMapsUrl: 'https://maps.google.com/?q=Lokmanya+Hospital+Chinchwad+Pune',
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&q=80&w=800',
    rating: 4.7,
    bedCount: 120,
    isVerified: true,
    verificationNote: 'NABH Accredited & Verified by ClinicCare'
  },
  {
    name: 'Surya Mother and Child Super Speciality Hospital',
    type: "Children's Hospital",
    area: 'Hinjewadi',
    address: 'Survey No. 8, Wakad-Hinjewadi Flyover, Bhujbal Chowk, Wakad, Pune 411057',
    phone: '020-67915555',
    emergencyAvailable: true,
    emergencyPhone: '020-67915555',
    departments: ['Pediatric ICU (PICU)', 'Neonatal ICU (NICU)', 'Pediatric Surgery', 'Maternity Care', 'Obstetrics'],
    openingHours: '24/7 Pediatric & Neonatal Emergency Care',
    website: 'https://suryahospitals.com',
    googleMapsUrl: 'https://maps.google.com/?q=Surya+Mother+and+Child+Hospital+Wakad+Pune',
    image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&q=80&w=800',
    rating: 4.9,
    bedCount: 150,
    isVerified: true,
    verificationNote: 'NABH Accredited & Verified by ClinicCare'
  },
  {
    name: 'Motherhood Hospital Kharadi',
    type: "Women's Hospital",
    area: 'Kharadi',
    address: 'Fountain Market, Kharadi, Pune 411014',
    phone: '020-67610000',
    emergencyAvailable: true,
    emergencyPhone: '020-67610000',
    departments: ['Obstetrics & Gynaecology', 'Fetal Medicine', 'Neonatology', 'Fertility Services', 'Pediatrics'],
    openingHours: '24/7 Maternity Emergency',
    website: 'https://motherhoodindia.com',
    googleMapsUrl: 'https://maps.google.com/?q=Motherhood+Hospital+Kharadi+Pune',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800',
    rating: 4.8,
    bedCount: 75,
    isVerified: true,
    verificationNote: 'NABH Accredited & Verified by ClinicCare'
  },
  {
    name: 'H. V. Desai Eye Hospital',
    type: 'Eye Hospital',
    area: 'Hadapsar',
    address: '93, Tarwade Vasti, Mohammadwadi, Hadapsar, Pune 411060',
    phone: '020-26970144',
    emergencyAvailable: true,
    emergencyPhone: '020-71966900',
    departments: ['Cataract', 'Cornea & Refractive', 'Glaucoma', 'Vitreo-Retina', 'Pediatric Ophthalmology', 'Eye Bank'],
    openingHours: '24/7 Eye Trauma & Emergency Services',
    website: 'https://hvdesai.org',
    googleMapsUrl: 'https://maps.google.com/?q=HV+Desai+Eye+Hospital+Pune',
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=800',
    rating: 4.9,
    bedCount: 300,
    isVerified: true,
    verificationNote: 'NABH Accredited Eye Hospital & Verified by ClinicCare'
  },
  {
    name: 'National Institute of Ophthalmology (NIO)',
    type: 'Eye Hospital',
    area: 'Shivajinagar',
    address: '1187/30, Off Ghole Road, Near Balgandharva Rang Mandir, Shivajinagar, Pune 411005',
    phone: '020-41460100',
    emergencyAvailable: true,
    emergencyPhone: '020-41460100',
    departments: ['LASIK', 'Cataract', 'Glaucoma', 'Medical Retina', 'Oculoplasty', 'Diabetic Eye Care'],
    openingHours: 'Mon-Sat 8:00 AM - 8:00 PM (Emergency 24/7)',
    website: 'https://nioeyecare.com',
    googleMapsUrl: 'https://maps.google.com/?q=National+Institute+of+Ophthalmology+Pune',
    image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=800',
    rating: 4.8,
    bedCount: 50,
    isVerified: true,
    verificationNote: 'NABH Accredited & Verified by ClinicCare'
  },
  {
    name: 'Cloudnine Hospital Shivajinagar',
    type: "Women's Hospital",
    area: 'Shivajinagar',
    address: 'Axon Building, Bhamburda, FC Road, Shivajinagar, Pune 411005',
    phone: '020-67924444',
    emergencyAvailable: true,
    emergencyPhone: '020-67924444',
    departments: ['Maternity Care', 'High-Risk Pregnancy', 'NICU Level III', 'Gynecology', 'Pediatrics'],
    openingHours: '24/7 Maternity Emergency',
    website: 'https://cloudninecare.com',
    googleMapsUrl: 'https://maps.google.com/?q=Cloudnine+Hospital+Shivajinagar+Pune',
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&q=80&w=800',
    rating: 4.8,
    bedCount: 65,
    isVerified: true,
    verificationNote: 'NABH Accredited & Verified by ClinicCare'
  },
  {
    name: 'Hardikar Hospital',
    type: 'Speciality',
    area: 'Shivajinagar',
    address: '1160/61, University Road, Ganeshkhind, Shivajinagar, Pune 411005',
    phone: '020-41031000',
    emergencyAvailable: true,
    emergencyPhone: '020-41031000',
    departments: ['Orthopedic Trauma', 'Joint Replacement', 'Arthroscopy', 'Spine Care', 'Physiotherapy'],
    openingHours: '24/7 Emergency Trauma Care',
    website: 'https://hardikarhospital.org',
    googleMapsUrl: 'https://maps.google.com/?q=Hardikar+Hospital+Pune',
    image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&q=80&w=800',
    rating: 4.7,
    bedCount: 100,
    isVerified: true,
    verificationNote: 'Verified by ClinicCare Healthcare Verification Team'
  },
  {
    name: 'Star Hospital Nigdi',
    type: 'Multispeciality',
    area: 'Nigdi',
    address: 'Spine Road, Sector 24, Pradhikaran, Nigdi, Pimpri-Chinchwad 411044',
    phone: '020-27650000',
    emergencyAvailable: true,
    emergencyPhone: '020-27650000',
    departments: ['Emergency Medicine', 'ICU', 'Cardiology', 'General Surgery', 'Obstetrics'],
    openingHours: '24/7 Emergency Services',
    website: 'https://starhospitalnigdi.com',
    googleMapsUrl: 'https://maps.google.com/?q=Star+Hospital+Nigdi+Pune',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800',
    rating: 4.5,
    bedCount: 80,
    isVerified: true,
    verificationNote: 'Verified by ClinicCare Healthcare Verification Team'
  },
  {
    name: 'Vitalife Medipoint Hospital',
    type: 'Multispeciality',
    area: 'Aundh',
    address: 'DP Road, Near Parihar Chowk, Aundh, Pune 411007',
    phone: '020-67266666',
    emergencyAvailable: true,
    emergencyPhone: '020-67266666',
    departments: ['Cardiology', 'General Surgery', 'Orthopedics', 'Pediatrics', 'Critical Care'],
    openingHours: '24/7 Emergency Services',
    website: 'https://medipointhospital.com',
    googleMapsUrl: 'https://maps.google.com/?q=Medipoint+Hospital+Aundh+Pune',
    image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=800',
    rating: 4.6,
    bedCount: 90,
    isVerified: true,
    verificationNote: 'NABH Accredited & Verified by ClinicCare'
  },
  {
    name: 'Mai Mangeshkar Hospital',
    type: 'Multispeciality',
    area: 'Warje',
    address: 'Survey No. 48/1, Near Mumbai-Bengaluru Highway, Warje, Pune 411058',
    phone: '020-40541000',
    emergencyAvailable: true,
    emergencyPhone: '020-40541000',
    departments: ['Critical Care', 'Internal Medicine', 'Cardiology', 'Gynaecology', 'Dialysis', 'Trauma'],
    openingHours: '24/7 Emergency & Inpatient Care',
    website: 'https://mmh.org.in',
    googleMapsUrl: 'https://maps.google.com/?q=Mai+Mangeshkar+Hospital+Warje+Pune',
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&q=80&w=800',
    rating: 4.7,
    bedCount: 120,
    isVerified: true,
    verificationNote: 'Verified by ClinicCare Healthcare Verification Team'
  },
  {
    name: 'CritiCare Asia Multispeciality Hospital',
    type: 'Multispeciality',
    area: 'Kothrud',
    address: 'Kothrud Depot Road, Gujrat Colony, Kothrud, Pune 411038',
    phone: '020-25381111',
    emergencyAvailable: true,
    emergencyPhone: '020-25381111',
    departments: ['Emergency Trauma', 'ICU', 'Cardiology', 'Pulmonology', 'Joint Replacement'],
    openingHours: '24/7 Emergency Services',
    website: 'https://criticareasiahospital.com',
    googleMapsUrl: 'https://maps.google.com/?q=CritiCare+Hospital+Kothrud+Pune',
    image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&q=80&w=800',
    rating: 4.6,
    bedCount: 110,
    isVerified: true,
    verificationNote: 'Verified by ClinicCare Healthcare Verification Team'
  },
  {
    name: 'Command Hospital Southern Command (CHSC)',
    type: 'Government',
    area: 'Wanowrie',
    address: 'Wanowrie, Pune Cantonment, Pune 411040',
    phone: '020-26361590',
    emergencyAvailable: true,
    emergencyPhone: '020-26361590',
    departments: ['Emergency & Trauma', 'Cardiothoracic Surgery', 'Neurosurgery', 'Oncology', 'Malignant Diseases'],
    openingHours: '24/7 Military & Referral Emergency',
    website: 'https://indianarmy.nic.in',
    googleMapsUrl: 'https://maps.google.com/?q=Command+Hospital+Southern+Command+Pune',
    image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&q=80&w=800',
    rating: 4.9,
    bedCount: 1050,
    isVerified: true,
    verificationNote: 'Apex Armed Forces Medical Institution & Verified by ClinicCare'
  }
];

const bloodBanksData = [
  {
    name: 'Jankalyan Raktakendra (Blood Centre)',
    area: 'Sadashiv Peth',
    address: '1003, Shukrawar Peth / Sadashiv Peth, Sarasbaug Chowk, Pune 411002',
    phone: '020-24449527',
    availableBloodGroups: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],
    donationAvailability: 'Voluntary Blood Donation Camp & Center (8:00 AM - 9:00 PM)',
    workingHours: '24 Hours Emergency Blood Issue',
    googleMapsUrl: 'https://maps.google.com/?q=Jankalyan+Raktakendra+Pune',
    hospitalAffiliation: 'Central Blood Bank & State Blood Transfusion Council (SBTC)',
    isVerified: true,
    verificationNote: 'FDA Approved & Certified Blood Centre'
  },
  {
    name: 'Poona Hospital Blood Bank',
    area: 'Sadashiv Peth',
    address: '27, Sadashiv Peth, Near Alka Talkies, Pune 411030',
    phone: '020-66096000',
    availableBloodGroups: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],
    donationAvailability: 'Donation Mon-Sun (9:00 AM - 7:00 PM)',
    workingHours: '24 Hours Emergency Blood Issue',
    googleMapsUrl: 'https://maps.google.com/?q=Poona+Hospital+Sadashiv+Peth+Pune',
    hospitalAffiliation: 'Poona Hospital and Research Centre',
    isVerified: true,
    verificationNote: 'FDA Licensed Blood Bank'
  },
  {
    name: 'Ruby Hall Clinic Blood Bank',
    area: 'Shivajinagar',
    address: '40, Sassoon Road, Sangamvadi, Pune 411001',
    phone: '020-66455100',
    availableBloodGroups: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],
    donationAvailability: 'Blood & Platelet Apheresis Donation 24/7',
    workingHours: '24/7 Round-the-clock Emergency Blood & Platelet Components',
    googleMapsUrl: 'https://maps.google.com/?q=Ruby+Hall+Clinic+Pune',
    hospitalAffiliation: 'Ruby Hall Clinic',
    isVerified: true,
    verificationNote: 'NABH Accredited Blood Centre'
  },
  {
    name: 'Deenanath Mangeshkar Hospital Blood Bank',
    area: 'Kothrud',
    address: 'Erandwane, Near Mhatre Bridge, Karve Road, Pune 411004',
    phone: '020-40151000',
    availableBloodGroups: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],
    donationAvailability: 'Voluntary Donation 8:00 AM - 8:00 PM',
    workingHours: '24 Hours Emergency Issue',
    googleMapsUrl: 'https://maps.google.com/?q=Deenanath+Mangeshkar+Hospital+Pune',
    hospitalAffiliation: 'Deenanath Mangeshkar Hospital',
    isVerified: true,
    verificationNote: 'FDA Approved & NABH Certified'
  },
  {
    name: 'Sassoon General Hospital Regional Blood Bank',
    area: 'Shivajinagar',
    address: 'Ground Floor, Sassoon Hospital Complex, Near Pune Station, Pune 411001',
    phone: '020-26128000',
    availableBloodGroups: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],
    donationAvailability: 'Government Voluntary Donation Camp & Walk-in',
    workingHours: '24/7 Emergency Blood Bank',
    googleMapsUrl: 'https://maps.google.com/?q=Sassoon+General+Hospital+Pune',
    hospitalAffiliation: 'Government B.J. Medical College & Sassoon Hospital',
    isVerified: true,
    verificationNote: 'Regional Blood Transfusion Centre (Govt of Maharashtra)'
  },
  {
    name: 'PCMC YCM Hospital Blood Bank',
    area: 'Pimpri',
    address: 'YCM Hospital Premises, Sant Tukaram Nagar, Pimpri, Pune 411018',
    phone: '020-27422500',
    availableBloodGroups: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],
    donationAvailability: 'Voluntary Donation Mon-Sat (8:00 AM - 6:00 PM)',
    workingHours: '24 Hours Emergency Issue',
    googleMapsUrl: 'https://maps.google.com/?q=YCM+Hospital+Pimpri+Pune',
    hospitalAffiliation: 'Pimpri-Chinchwad Municipal Corporation',
    isVerified: true,
    verificationNote: 'Government Municipal Blood Centre'
  },
  {
    name: 'Aditya Birla Memorial Hospital Blood Centre',
    area: 'Chinchwad',
    address: 'Aditya Birla Hospital Marg, Thergaon, Chinchwad, Pune 411033',
    phone: '020-30717500',
    availableBloodGroups: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],
    donationAvailability: 'Blood & Component Donation Mon-Sun',
    workingHours: '24 Hours Emergency Issue',
    googleMapsUrl: 'https://maps.google.com/?q=Aditya+Birla+Memorial+Hospital+Chinchwad+Pune',
    hospitalAffiliation: 'Aditya Birla Memorial Hospital',
    isVerified: true,
    verificationNote: 'FDA Licensed & NABH Accredited'
  },
  {
    name: 'Noble Hospital Blood Bank',
    area: 'Hadapsar',
    address: '153, Magarpatta City Road, Hadapsar, Pune 411013',
    phone: '020-66285000',
    availableBloodGroups: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],
    donationAvailability: 'Voluntary Donation 9:00 AM - 8:00 PM',
    workingHours: '24 Hours Emergency Issue',
    googleMapsUrl: 'https://maps.google.com/?q=Noble+Hospital+Hadapsar+Pune',
    hospitalAffiliation: 'Noble Hospital',
    isVerified: true,
    verificationNote: 'FDA Approved Blood Bank'
  }
];

const eyeCareCentresData = [
  {
    name: 'H. V. Desai Eye Hospital',
    area: 'Hadapsar',
    address: '93, Tarwade Vasti, Mohammadwadi, Hadapsar, Pune 411060',
    phone: '020-26970144',
    categories: ['Eye Testing', 'Cataract', 'Glaucoma', 'Retina', 'LASIK', 'Cornea', 'Pediatric Eye Care', 'Diabetic Eye Care', 'Emergency Eye Care', 'Eye Donation'],
    services: ['Micro-Incision Cataract Surgery (MICS)', 'Contoura Vision LASIK', 'Retina Laser & Vitrectomy', 'Cornea Transplantation', '24/7 Eye Trauma Emergency', 'Eye Bank & Eye Donation Hotline'],
    openingHours: '24 Hours Emergency & Mon-Sat 8:00 AM - 6:00 PM OPD',
    googleMapsUrl: 'https://maps.google.com/?q=HV+Desai+Eye+Hospital+Pune',
    website: 'https://hvdesai.org',
    rating: 4.9,
    isVerified: true,
    verificationNote: 'NABH Accredited Super-Speciality Eye Institute'
  },
  {
    name: 'National Institute of Ophthalmology (NIO)',
    area: 'Shivajinagar',
    address: '1187/30, Off Ghole Road, Near Balgandharva Rang Mandir, Shivajinagar, Pune 411005',
    phone: '020-41460100',
    categories: ['Eye Testing', 'Cataract', 'Glaucoma', 'Retina', 'LASIK', 'Cornea', 'Pediatric Eye Care', 'Diabetic Eye Care'],
    services: ['Blade-free Femto LASIK', 'Phacoemulsification Cataract Surgery', 'Optical Coherence Tomography (OCT)', 'Squint Correction', 'Glaucoma Shunt Surgery'],
    openingHours: 'Mon - Sat: 8:30 AM - 8:00 PM',
    googleMapsUrl: 'https://maps.google.com/?q=National+Institute+of+Ophthalmology+Pune',
    website: 'https://nioeyecare.com',
    rating: 4.8,
    isVerified: true,
    verificationNote: 'NABH Accredited & Leading Eye Hospital in Pune'
  },
  {
    name: 'Asian Eye Hospital & Laser Institute',
    area: 'Deccan',
    address: 'Sakar Building, Opp. Garware College, Karve Road, Deccan Gymkhana, Pune 411004',
    phone: '020-25442828',
    categories: ['Eye Testing', 'Cataract', 'LASIK', 'Retina', 'Glaucoma', 'Diabetic Eye Care'],
    services: ['Refractive SMILE & LASIK', 'Multifocal IOL Cataract', 'Diabetic Retinopathy Management', 'Dry Eye Therapy'],
    openingHours: 'Mon - Sat: 9:00 AM - 7:30 PM',
    googleMapsUrl: 'https://maps.google.com/?q=Asian+Eye+Hospital+Karve+Road+Pune',
    website: 'https://asianeyehospital.com',
    rating: 4.7,
    isVerified: true,
    verificationNote: 'Certified Eye Care Center'
  },
  {
    name: 'Dr. Agarwals Eye Hospital Kothrud',
    area: 'Kothrud',
    address: 'Opposite Karishma Complex, Sangam Press Road, Kothrud, Pune 411038',
    phone: '020-67123456',
    categories: ['Eye Testing', 'Cataract', 'Glaucoma', 'Retina', 'LASIK', 'Pediatric Eye Care'],
    services: ['Glued IOL Technique', 'PDEK Cornea Surgery', 'Custom LASIK', 'Computerized Eye Testing', 'Neuro-Ophthalmology'],
    openingHours: 'Mon - Sat: 9:00 AM - 8:00 PM, Sun: 10:00 AM - 1:00 PM',
    googleMapsUrl: 'https://maps.google.com/?q=Dr+Agarwals+Eye+Hospital+Kothrud+Pune',
    website: 'https://dragarwal.com',
    rating: 4.8,
    isVerified: true,
    verificationNote: 'Premier Eye Care Network'
  },
  {
    name: 'Sharp Sight Eye Hospital Aundh',
    area: 'Aundh',
    address: 'Near Parihar Chowk, DP Road, Aundh, Pune 411007',
    phone: '020-49112233',
    categories: ['Eye Testing', 'Cataract', 'LASIK', 'Retina', 'Diabetic Eye Care'],
    services: ['Robotic Cataract Surgery', 'Contoura Vision', 'Pediatric Vision Screening', 'Spectacle Removal Surgery'],
    openingHours: 'Mon - Sat: 9:00 AM - 7:00 PM',
    googleMapsUrl: 'https://maps.google.com/?q=Sharp+Sight+Eye+Hospital+Aundh+Pune',
    website: 'https://sharpsight.in',
    rating: 4.7,
    isVerified: true,
    verificationNote: 'Accredited Eye Hospital'
  },
  {
    name: 'Wavikar Eye Institute Baner',
    area: 'Baner',
    address: 'Baner Road, Near Amar Business Park, Baner, Pune 411045',
    phone: '020-66778899',
    categories: ['Eye Testing', 'Cataract', 'Cornea', 'LASIK', 'Glaucoma', 'Emergency Eye Care'],
    services: ['Blade-free Cataract', 'ICL Implantation', 'Advanced Corneal Cross-Linking (C3R)', 'Glaucoma Valve Surgery'],
    openingHours: 'Mon - Sat: 9:00 AM - 8:00 PM',
    googleMapsUrl: 'https://maps.google.com/?q=Wavikar+Eye+Institute+Baner+Pune',
    website: 'https://wavikareye.com',
    rating: 4.8,
    isVerified: true,
    verificationNote: 'Accredited Eye Hospital'
  },
  {
    name: 'Phadke Eye Clinic Pimpri-Chinchwad',
    area: 'Chinchwad',
    address: 'Opp. Chinchwad Post Office, Old Mumbai-Pune Highway, Chinchwad, Pune 411033',
    phone: '020-27471122',
    categories: ['Eye Testing', 'Cataract', 'Glaucoma', 'Retina', 'Diabetic Eye Care'],
    services: ['Comprehensive Eye Exam', 'Laser Cataract', 'Glaucoma Detection', 'Medical Retina Evaluation'],
    openingHours: 'Mon - Sat: 9:30 AM - 6:30 PM',
    googleMapsUrl: 'https://maps.google.com/?q=Phadke+Eye+Clinic+Chinchwad+Pune',
    website: 'https://phadkeeyeclinic.com',
    rating: 4.6,
    isVerified: true,
    verificationNote: 'Established Pimpri-Chinchwad Eye Clinic'
  }
];

module.exports = { hospitalsData, bloodBanksData, eyeCareCentresData };
